[default]

# executable = "arma3_x64"        # Default: "arma3_x64"
# file_patching = true # Default: true
# binarize = false # Default: false
# rapify = true # Default: true

workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
    "2964055294", # Munitions Armory
]

dlc = []
optionals = []


parameters = [
    "-noPause",
    "-noPauseAudio",
]

[Test]
extends = "default"
mission = "test.VR"